version: "3.8"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-local
    restart: unless-stopped
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${MSSQL_ADMIN_PASSWORD}"
      MSSQL_PID: "${MSSQL_PID:-Developer}"
#     volumes:
#       - mssql-data:/var/opt/mssql

# volumes:
#   mssql-data: {}
